<script lang="ts">
	import type { ResearchNote } from '$lib/types';
	import { notes, loadNotes, loadNote, currentNote, createNote } from '$lib/stores/notes';
	import { openNote as openNoteTab } from '$lib/stores/tabs';
	import NoteList from './NoteList.svelte';
	import NoteViewer from './NoteViewer.svelte';
	import NoteEditor from './NoteEditor.svelte';
	import { X, Maximize2, Square, FileText, Plus, ExternalLink } from 'lucide-svelte';
	import { onMount } from 'svelte';
	import { api } from '$lib/api/client';
	import { toast } from '$lib/stores/toast';

	interface Props {
		paperId?: string | null;
		initialNoteId?: string | null;
		onClose: () => void;
	}

	type PanelSize = 'small' | 'medium' | 'large';
	type PanelMode = 'list' | 'view' | 'edit';

	let { paperId = null, initialNoteId = null, onClose }: Props = $props();

	// Panel state
	let panelMode: PanelMode = $state('list');
	let currentNoteId = $state<string | null>(initialNoteId);
	let panelSize: PanelSize = $state('medium');
	let position = $state({ x: 0, y: 0 });
	let isDragging = $state(false);
	let dragOffset = { x: 0, y: 0 };

	// Template state
	let autoGeneratedTitle = $state<string>('');
	let autoGeneratedContent = $state<string>('');
	let isLoadingTemplate = $state(false);

	// Size configurations
	const sizeConfig = {
		small: { width: 400, height: 600 },
		medium: { width: 700, height: 800 },
		large: { width: '90vw', height: '90vh' }
	};

	// Load notes on mount
	onMount(async () => {
		const savedSize = localStorage.getItem('notePanelSize') as PanelSize | null;

		if (savedSize && ['small', 'medium', 'large'].includes(savedSize)) {
			panelSize = savedSize;
		}

		// Position based on size
		if (panelSize === 'large') {
			const savedPosition = localStorage.getItem('notePanelPosition-large');
			if (savedPosition) {
				try {
					position = JSON.parse(savedPosition);
				} catch {
					centerPanel();
				}
			} else {
				centerPanel();
			}
		} else {
			positionBottomRight();
		}

		// Load notes list
		await loadNotes();

		// If paperId is provided, check for existing notes or create one
		if (paperId) {
			const result = await api.getNotesByPaper(paperId);
			if (result.success && result.data && result.data.length > 0) {
				// Open the first paper note
				currentNoteId = result.data[0].id;
				await loadNote(currentNoteId);
				panelMode = 'view';
			} else {
				// No notes for this paper, generate template
				panelMode = 'edit';
				isLoadingTemplate = true;
				const templateResult = await api.generateNoteTemplate(paperId);
				if (templateResult.success && templateResult.data) {
					autoGeneratedTitle = templateResult.data.title;
					autoGeneratedContent = templateResult.data.template;
				}
				isLoadingTemplate = false;
			}
		} else if (initialNoteId) {
			// Open specific note
			currentNoteId = initialNoteId;
			await loadNote(currentNoteId);
			panelMode = 'view';
		}
	});

	function centerPanel() {
		const config = sizeConfig[panelSize];
		const width = typeof config.width === 'string' ? window.innerWidth * 0.9 : config.width;
		const height = typeof config.height === 'string' ? window.innerHeight * 0.9 : config.height;

		position = {
			x: (window.innerWidth - width) / 2,
			y: (window.innerHeight - height) / 2
		};
	}

	function positionBottomRight() {
		const config = sizeConfig[panelSize];
		const width = typeof config.width === 'string' ? window.innerWidth * 0.9 : config.width;
		const height = typeof config.height === 'string' ? window.innerHeight * 0.9 : config.height;

		position = {
			x: window.innerWidth - width - 20,
			y: window.innerHeight - height - 20
		};
	}

	function changeSize(newSize: PanelSize) {
		panelSize = newSize;
		localStorage.setItem('notePanelSize', newSize);

		// Large size goes to center, others to bottom right
		if (newSize === 'large') {
			centerPanel();
		} else {
			positionBottomRight();
		}
	}

	function handleMouseDown(e: MouseEvent) {
		if ((e.target as HTMLElement).closest('.no-drag')) return;

		isDragging = true;
		dragOffset = {
			x: e.clientX - position.x,
			y: e.clientY - position.y
		};
	}

	function handleMouseMove(e: MouseEvent) {
		if (!isDragging) return;

		position = {
			x: e.clientX - dragOffset.x,
			y: e.clientY - dragOffset.y
		};

		// Only save position for large size
		if (panelSize === 'large') {
			localStorage.setItem('notePanelPosition-large', JSON.stringify(position));
		}
	}

	function handleMouseUp() {
		isDragging = false;
	}

	function handleSelectNote(note: ResearchNote) {
		currentNoteId = note.id;
		loadNote(note.id);
		panelMode = 'view';
	}

	async function handleCreateNote() {
		panelMode = 'edit';
		currentNoteId = null;
	}

	async function handleSaveNote(title: string, content: string) {
		if (currentNoteId) {
			// Update existing note
			const success = await api.updateNote(currentNoteId, { title, content, paperId });
			if (success) {
				await loadNote(currentNoteId);
				await loadNotes();
				panelMode = 'view';
			}
		} else {
			// Create new note
			const note = await createNote(title, content, paperId);
			if (note) {
				currentNoteId = note.id;
				await loadNote(note.id);
				panelMode = 'view';
			}
		}
	}

	function handleCancelEdit() {
		if (currentNoteId) {
			panelMode = 'view';
		} else {
			panelMode = 'list';
		}
	}

	function handleBackToList() {
		currentNoteId = null;
		panelMode = 'list';
	}

	function handleEdit() {
		panelMode = 'edit';
	}

	function handleNavigateToNote(noteId: string) {
		currentNoteId = noteId;
		loadNote(noteId);
		panelMode = 'view';
	}

	function handleNavigateToPaper(paperId: string) {
		// TODO: Open paper in viewer
		console.log('Navigate to paper:', paperId);
	}

	function handleFullScreen() {
		if (currentNoteId && $currentNote) {
			openNoteTab($currentNote.note);
			onClose();
		}
	}

	// Current size config
	const currentSize = $derived(sizeConfig[panelSize]);
	const widthStyle = $derived(
		typeof currentSize.width === 'string' ? currentSize.width : `${currentSize.width}px`
	);
	const heightStyle = $derived(
		typeof currentSize.height === 'string' ? currentSize.height : `${currentSize.height}px`
	);

	const panelTitle = $derived(
		panelMode === 'list'
			? 'Research Notes'
			: panelMode === 'edit'
				? currentNoteId
					? 'Edit Note'
					: 'New Note'
				: $currentNote?.note.title || 'Note'
	);
</script>

<svelte:window onmousemove={handleMouseMove} onmouseup={handleMouseUp} />

<div
	class="fixed bg-white/95 dark:bg-gray-900/95 backdrop-blur-xl rounded-2xl shadow-2xl border border-gray-200 dark:border-gray-700 overflow-hidden flex flex-col z-50"
	style="left: {position.x}px; top: {position.y}px; width: {widthStyle}; height: {heightStyle}; cursor: {isDragging
		? 'grabbing'
		: 'default'};"
>
	<!-- Header -->
	<div class="bg-gradient-to-r from-emerald-600 to-teal-600">
		<div
			class="px-4 py-2 flex items-center justify-between cursor-grab active:cursor-grabbing"
			onmousedown={handleMouseDown}
		>
			<div class="flex items-center gap-2 flex-1 min-w-0 overflow-hidden">
				<FileText class="w-4 h-4 text-white shrink-0" />
				<h3 class="font-semibold text-white truncate">{panelTitle}</h3>
				{#if paperId}
					<span class="text-xs text-white/70">Linked to paper</span>
				{/if}
			</div>

			<div class="flex items-center gap-1 no-drag shrink-0">
				<!-- Full screen button (only in view mode) -->
				{#if panelMode === 'view' && currentNoteId}
					<button
						onclick={handleFullScreen}
						class="p-1.5 hover:bg-white/20 rounded transition-colors"
						title="Open in tab"
					>
						<ExternalLink class="w-3.5 h-3.5 text-white" />
					</button>
				{/if}

				<!-- Size buttons -->
				<button
					onclick={() => changeSize('small')}
					class="p-1.5 hover:bg-white/20 rounded transition-colors {panelSize === 'small'
						? 'bg-white/30'
						: ''}"
					title="Small"
				>
					<div class="w-3 h-3 border border-white rounded"></div>
				</button>
				<button
					onclick={() => changeSize('medium')}
					class="p-1.5 hover:bg-white/20 rounded transition-colors {panelSize === 'medium'
						? 'bg-white/30'
						: ''}"
					title="Medium"
				>
					<Square class="w-3.5 h-3.5 text-white" />
				</button>
				<button
					onclick={() => changeSize('large')}
					class="p-1.5 hover:bg-white/20 rounded transition-colors {panelSize === 'large'
						? 'bg-white/30'
						: ''}"
					title="Large"
				>
					<Maximize2 class="w-3.5 h-3.5 text-white" />
				</button>

				<!-- Close button -->
				<button
					onclick={onClose}
					class="p-1.5 hover:bg-white/20 rounded transition-colors"
					title="Close"
				>
					<X class="w-4 h-4 text-white" />
				</button>
			</div>
		</div>
	</div>

	<!-- Content -->
	<div class="flex-1 overflow-hidden">
		{#if panelMode === 'list'}
			<NoteList onSelectNote={handleSelectNote} onCreateNote={handleCreateNote} />
		{:else if panelMode === 'view' && currentNoteId}
			<NoteViewer
				noteId={currentNoteId}
				onBack={handleBackToList}
				onEdit={handleEdit}
				onNavigateToNote={handleNavigateToNote}
				onNavigateToPaper={handleNavigateToPaper}
			/>
		{:else if panelMode === 'edit'}
			<NoteEditor
				title={$currentNote?.note.title || autoGeneratedTitle}
				content={$currentNote?.note.content || autoGeneratedContent}
				onSave={handleSaveNote}
				onCancel={handleCancelEdit}
				isLoading={isLoadingTemplate}
			/>
		{/if}
	</div>
</div>
